### ISSUE TITLE
斗 为什么 拆成 “⺀”和“十” 而且不是 “十”和“⺀”

### ISSUE THREAD

**Issue by UFDXD** [gaboolic/moqima-tables#2]
自然码 原来的辅码 是⺀”和“十”  很直观
![image_97](https://github.com/user-attachments/assets/a8fb7fdf-3555-4c34-b7fa-184f97e7ef59)
墨奇是
![image_98](https://github.com/user-attachments/assets/1fed6de7-c117-4ca7-ab58-54084f9776f3)
我是第一次使用双拼+辅码的，觉得 墨奇的拆分，有的不按开始笔画顺序拆分，我个人难以识别末笔。
比如这个”斗“
字典开笔是“⺀”末笔是“十” 的” l “ ，正常书写习惯也是这样
![image](https://github.com/user-attachments/assets/4d93c0d7-7e0b-407a-b7cf-d760d4265463)
但是墨奇码中我第一次拆”⺀”就错了。

所以请问这是不是一种墨奇码的特点，是不是个别，还是普遍现象。

**Comment by gaboolic** [comment]
嵌套结构，字形不相交：由大到小 爽->大乂，噩->王口，类似包围结构由外及内
例如：坐，是先拆 土 再拆人 人
头 先拆 大 再拆 ⺀
斗 先拆 十 再拆 ⺀

**Comment by UFDXD** [comment]
感谢
